### ISSUE TITLE
[docker] list

### ISSUE THREAD

**Issue by Alice52** [Alice52/java-ocean#180]

**Comment by Alice52** [comment]
## sample script

```yml
version: '3'
services:
  dev-eureka:
    build:
      context: ./eureka
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8761:8761
    container_name: dev-eureka
    hostname: dev-eureka
    extra_hosts:
      - 'dev-mysql:${dev_mysql}'
      - 'dev-redis:${dev_redis}'
    image: dev-eureka:${TAG:-latest}-stg
```
