### ISSUE TITLE
[cloud] build nacos image

### ISSUE THREAD

**Issue by Alice52** [Alice52/java-ocean#191]
- [x] 1. use embed database.
```yml
version: '2.4'
services:
  nacos:
    image: nacos/nacos-server:2.0.1
    restart: 'always'
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - JVM_XMS=256m
      - JVM_XMX=256m
      - JVM_Xmn=128m
    volumes:
      - /root/nacos/logs/standalone-logs:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    # http://101.37.174.197:8848/nacos/#/login  nacos/nacos
```
